### ISSUE TITLE
About the Calculation of Motion Intersity Bucket

### ISSUE THREAD

**Issue by jiangzhengkai** [maxin-cn/Cinemo#1]
Hi, how do you calculate the motion intersity bucket?

**Comment by maxin-cn** [comment]
> Hi, how do you calculate the motion intersity bucket?

Hi, thanks for your interest. Please wait for our paper.

**Comment by maxin-cn** [comment]
Hi @jiangzhengkai, our paper is released on arxiv. You can find the way to calculate the motion intensity.
