### ISSUE TITLE
Is it able to generate video longer than 15 frames?

### ISSUE THREAD

**Issue by cc13qq** [maxin-cn/Cinemo#13]
I've tried more video frames with the pre-trained model, but the results seem abnormal.
Is this model able to generate video longer than 15 frames? Or is it just applicable for 15 frames at most?

**Comment by maxin-cn** [comment]
Thank you for your interest. I think we can use something like autoregressive to make it generate longer videos. Increasing the length of the video directly while reasoning will result in a mismatch with the training Settings.

**Comment by johndpope** [comment]
maybe helpful - https://arxiv.org/html/2405.11473v1
