### ISSUE TITLE
Output video duration

### ISSUE THREAD

**Issue by superbagus1712** [maxin-cn/Cinemo#14]
I am very happy to use it. I want to ask how to change the video duration to 10 seconds or more?

**Comment by maxin-cn** [comment]
Thank you very much for your interest. Our model is trained on video clips of approximately 16 frames, so directly increasing the video length during testing leads to distorted content. I think we can use the last frame of the previous clip as the first frame for the next inference clip, generating long videos autoregressively.

**Comment by superbagus1712** [comment]
can you show me which part to modify about that ?

**Comment by maxin-cn** [comment]
Please see here:
https://github.com/maxin-cn/Cinemo/blob/f2bf6c447edda81b9b218bbdd2bfdb4a9a0f86e1/pipelines/animation.py#L85

Just use the last frame of the previous clip as the first frame for the next inference clip. You can also change the prompt.
