### ISSUE TITLE
Add a local demo

### ISSUE THREAD

**Issue by yvrjsharma** [maxin-cn/Cinemo#3]
It would be really helpful to have the huggingface Spaces demo available locally, with a link and setup instructions in the README. I saw the LivePortrait repo doing something similar here - https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#4-gradio-interface- and thought it was a great idea. Makes it so much easier to test and contribute!

Reference LivePortrait Example:
![image](https://github.com/user-attachments/assets/8bf08409-0f3e-4b8a-a0d0-d0ac60996606)

Cinemo demo on Huggingface Spaces:
![image](https://github.com/user-attachments/assets/e377d94a-0104-417a-8b2b-a589b51b2959)

**Comment by maxin-cn** [comment]
Thanks for your suggestion. I will put `Huggingface Spaces demo` code into this repository.

**Comment by maxin-cn** [comment]
I have added the local demo. I appreciate your suggestion.

**Comment by yvrjsharma** [comment]
Awesome, thanks for a prompt action on this 🙌 I'll go ahead and close this issue.
