### ISSUE TITLE
Can't load GRadio

### ISSUE THREAD

**Issue by magekinnarus** [maxin-cn/Cinemo#4]
This is the error I encountered:

(cinemo) H:\Cinemo>python app.py
Traceback (most recent call last):
  File "H:\Cinemo\app.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

I am running this in Windows 11. Is this why it isn't working?

**Comment by maxin-cn** [comment]
Hi, thanks for your interest. Please install `gradio` by running `pip install gradio`.
