### ISSUE TITLE
Could not find DiT checkpoint

### ISSUE THREAD

**Issue by taiyouZhang** [maxin-cn/Cinemo#5]
Thanks for great jobs!
Try to use sample.yaml and have no idea about where I can download this checkpoint
```ckpt: /mnt/lustre/maxin/work/animation/animation-v6/results_qt_003-UNet-pixabaylaion-Xfor-Gc-320_512_0303000.pt```

**Comment by taiyouZhang** [comment]
just use `cinemo.pt`  I guess ?

**Comment by maxin-cn** [comment]
Thanks for your interest. `ckpt` is not used. You  should use this (https://github.com/maxin-cn/Cinemo/blob/61350936846abf545c07b4928a9f4159deabab5a/configs/sample.yaml#L6).

**Comment by maxin-cn** [comment]
All model weights can be found here (https://huggingface.co/maxin-cn/Cinemo/tree/main).  If you use the script in this repo，all related weights will be download automatically.
